[package]
name = "rs_immu"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"
tonic = "0.12"
prost = "0.13.4"   # 最新バージョンに統一
log = "0.4"
env_logger = "0.10"
warp = "0.3" 
prost-types = "0.13.4"
tokio = { version = "1.28", features = ["rt-multi-thread", "macros"] }

[build-dependencies]
tonic-build = "0.12"

[dev-dependencies]
uuid = { version = "1.4", features = ["v4"] } # ランダムキー生成
tokio = { version = "1", features = ["full"] } # 非同期テスト用

[env]
PROTOC_INCLUDE = "D:\\city_chain_project\\proto\\include"

[lib]
name = "rs_immu"
path = "src/lib.rs"

[[bin]]
name = "main_immudb"
path = "src/bin/main_immudb.rs"

[[test]]
name = "test_immudb"
path = "tests/test_immudb.rs"