# .pre-commit-config.yaml （最小・落ちにくい衛生チェックだけ）
default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-yaml
        files: ^(services\.yaml|\.github/workflows/.*\.ya?ml)$
      - id: check-json
        files: ^.*\.json$

  # Python は E/F/I（構文・未定義・import順）だけ自動修正まで。
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--select=E,F,I", "--fix"]
        files: ^DAGs/.+/_python/.*\.py$

# ポイント
# シークレット検知は入れていません（ここが赤の元凶）。
# Rust の整形/リントは外しました（CI か手元で cargo fmt する想定）。
# YAML/JSON と Python の超基本だけ。まずはこれで緑にする。