# .pre-commit-config.yaml  --- minimal & pass-first
minimum_pre_commit_version: "3.6.0"

# 生成物・巨大ディレクトリは最初から検査対象外
exclude: |
  (?x)^(
    \.git/|
    \.venv/|
    venv/|
    target/|
    target-release/|
    dist/|
    build/|
    DAGs/.*/target/|
    DAGs/.*/dist/|
    DAGs/.*/node_modules/|
    docker-bake\.generated\.hcl|
    docker-compose\..*\.generated\.yml|
    .*\.whl|.*\.zip|.*\.jar
  )$

repos:
  # まずは「衛生系」だけ（落ちにくい、直せても自動で直る）
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
      - id: detect-private-key

# ★ Ruff/Black/Flake8 など重い静的解析は一旦入れない（まず緑にする）
