# .pre-commit-config.yaml （最小・落ちにくい衛生チェックだけ）
# シンプル＆最小構成。まずは“緑”を優先
minimum_pre_commit_version: "3.5.0"

files: >
  ^(
    DAGs/libs/algorithm/poh_holdmetrics/|
    tools/|
    services\.yaml|
    Dockerfile|
    noxfile\.py|
    Cargo\.toml
  )

exclude: >
  ^(
    \.git/|
    \.venv/|
    target/|
    dist/|
    build/|
    node_modules/|
    network/|                # ← 大量データは見ない
    android_studio/|
    .*\.pem$|.*\.key$|.*\.crt$|   # 秘密鍵検出系の誤爆回避
    .*\.bin$|
    .*\.proto\.json$|
    .*\.pb$|
    .*\.descriptor$
  )

repos:
  # 末尾スペースや改行など最低限だけチェック
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]

  # Python: まずは ruff のフォーマッタだけ（速度重視）
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        additional_dependencies: []
      - id: ruff-format

  # TOML / YAML の軽いバリデーション
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        files: "^(services\\.yaml|\\.github/workflows/.*\\.ya?ml)$"
        args: [-d, "{extends: default, rules: {line-length: disable}}"]

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort-fix
        files: "^(.+\\.toml)$"
