version: 1
defaults:
  network: city_chain_net
  dockerfile: ./Dockerfile
pyext:
- name: rvh_trace
  crate_path: DAGs/libs/algorithm/rvh_trace
  kind: mixed
  features:
  - python
  python_wrapper: DAGs/libs/algorithm/rvh_trace/rvh_trace_python
  tests:
  - kind: pytest
    path: DAGs/libs/algorithm/rvh_trace/rvh_trace_python/rvh_trace/tests
    env: {}
- name: poh_holdmetrics
  crate_path: DAGs/libs/algorithm/poh_holdmetrics
  kind: mixed
  features:
  - python
  python_wrapper: DAGs/libs/algorithm/poh_holdmetrics/poh_holdmetrics_python
  tests:
  - kind: pytest
    path: DAGs/libs/algorithm/poh_holdmetrics/poh_holdmetrics_python/poh_holdmetrics/tests
    env:
      MONGODB_DB: pytest_tmp
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION_VERSION: '3'
      POH_DISABLE_RUST: '1'
      PYTEST_ADDOPTS: -o cache_dir=/tmp/pytest_cache
services:
- name: poh_holdmetrics-grpc
  crate_path: DAGs/libs/algorithm/poh_holdmetrics/poh_holdmetrics_rust
  kind: rust
  bin_name: main_holdmetrics
  env:
    SERVICE_MODE: grpc
    GRPC_ADDRESS: 0.0.0.0:60051
    MONGODB_URL: ${MONGODB_URL}
    MONGODB_DB: holdmetrics_prod
  ports:
  - 60051:60051
  - 9100:9100
  command:
  - /app/bin/main_holdmetrics
  - --grpc-addr
  - 0.0.0.0:60051
  healthcheck:
    port: 60051
    interval: 5s
    timeout: 2s
    retries: 20
- name: poh_holdmetrics-http
  crate_path: DAGs/libs/algorithm/poh_holdmetrics/poh_holdmetrics_rust
  kind: mixed
  features:
  - python
  env:
    SERVICE_MODE: http
    HTTP_PORT: '8000'
    MONGODB_URL: ${MONGODB_URL}
    MONGODB_DB: holdmetrics_prod
  ports:
  - 8000:8000
  command:
  - python
  - -m
  - uvicorn
  - poh_holdmetrics.api.http_server:app
  - --host
  - 0.0.0.0
  - --port
  - '8000'
  healthcheck:
    port: 8000
    interval: 5s
    timeout: 2s
    retries: 20
