[package]
name = "cert_rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
base64 = "0.21"
once_cell = "1"
regex = "1"
hex = "0.4"
rand = "0.8"
