# city_chain_project\network\DAGs\common\proto\storage_pb2_grpc.py
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import proto.storage_pb2 as storage__pb2


class StorageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreFragment = channel.unary_unary(
                '/storage.StorageService/StoreFragment',
                request_serializer=storage__pb2.ShardRequest.SerializeToString,
                response_deserializer=storage__pb2.StoreResponse.FromString,
                )


class StorageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StoreFragment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreFragment': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreFragment,
                    request_deserializer=storage__pb2.ShardRequest.FromString,
                    response_serializer=storage__pb2.StoreResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'storage.StorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))

 # This class is part of an EXPERIMENTAL API.


class StorageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StoreFragment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/storage.StorageService/StoreFragment',
            storage__pb2.ShardRequest.SerializeToString,
            storage__pb2.StoreResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
