[package]
name    = "dilithium-Android-ClientCert"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni                 = "0.21"
pqcrypto-dilithium  = "0.5"
pqcrypto-traits     = "0.3"
