[package]
name = "rsmongodb"
version = "0.1.0"
edition = "2021"

[dependencies]
mongodb = { version = "2.8.2", features = ["sync"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"
tokio = { version = "1", features = ["full"] }

[lib]
name = "rsmongodb"
path = "src/lib.rs"

[[bin]]
name = "main_rsmongodb"
path = "src/bin/main_rsmongodb.rs"

[[test]]
name = "test_rsmongodb"
path = "tests/test_rsmongodb.rs"