[package]
name = "flag_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "flag_rust"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
serde_json = "1"
rayon = "1"
