# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import immudb_pb2 as schema_dot_immudb__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in schema/immudb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImmuServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/immudb.ImmuService/Login',
                request_serializer=schema_dot_immudb__pb2.LoginRequest.SerializeToString,
                response_deserializer=schema_dot_immudb__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/immudb.ImmuService/Logout',
                request_serializer=schema_dot_immudb__pb2.LogoutRequest.SerializeToString,
                response_deserializer=schema_dot_immudb__pb2.LogoutResponse.FromString,
                _registered_method=True)
        self.Set = channel.unary_unary(
                '/immudb.ImmuService/Set',
                request_serializer=schema_dot_immudb__pb2.SetRequest.SerializeToString,
                response_deserializer=schema_dot_immudb__pb2.SetResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/immudb.ImmuService/Get',
                request_serializer=schema_dot_immudb__pb2.GetRequest.SerializeToString,
                response_deserializer=schema_dot_immudb__pb2.GetResponse.FromString,
                _registered_method=True)
        self.MultiSet = channel.unary_unary(
                '/immudb.ImmuService/MultiSet',
                request_serializer=schema_dot_immudb__pb2.MultiSetRequest.SerializeToString,
                response_deserializer=schema_dot_immudb__pb2.MultiSetResponse.FromString,
                _registered_method=True)
        self.Scan = channel.unary_unary(
                '/immudb.ImmuService/Scan',
                request_serializer=schema_dot_immudb__pb2.ScanRequest.SerializeToString,
                response_deserializer=schema_dot_immudb__pb2.ScanResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/immudb.ImmuService/Delete',
                request_serializer=schema_dot_immudb__pb2.DeleteRequest.SerializeToString,
                response_deserializer=schema_dot_immudb__pb2.DeleteResponse.FromString,
                _registered_method=True)


class ImmuServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Set(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MultiSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Scan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImmuServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=schema_dot_immudb__pb2.LoginRequest.FromString,
                    response_serializer=schema_dot_immudb__pb2.LoginResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=schema_dot_immudb__pb2.LogoutRequest.FromString,
                    response_serializer=schema_dot_immudb__pb2.LogoutResponse.SerializeToString,
            ),
            'Set': grpc.unary_unary_rpc_method_handler(
                    servicer.Set,
                    request_deserializer=schema_dot_immudb__pb2.SetRequest.FromString,
                    response_serializer=schema_dot_immudb__pb2.SetResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=schema_dot_immudb__pb2.GetRequest.FromString,
                    response_serializer=schema_dot_immudb__pb2.GetResponse.SerializeToString,
            ),
            'MultiSet': grpc.unary_unary_rpc_method_handler(
                    servicer.MultiSet,
                    request_deserializer=schema_dot_immudb__pb2.MultiSetRequest.FromString,
                    response_serializer=schema_dot_immudb__pb2.MultiSetResponse.SerializeToString,
            ),
            'Scan': grpc.unary_unary_rpc_method_handler(
                    servicer.Scan,
                    request_deserializer=schema_dot_immudb__pb2.ScanRequest.FromString,
                    response_serializer=schema_dot_immudb__pb2.ScanResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=schema_dot_immudb__pb2.DeleteRequest.FromString,
                    response_serializer=schema_dot_immudb__pb2.DeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'immudb.ImmuService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('immudb.ImmuService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImmuService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/immudb.ImmuService/Login',
            schema_dot_immudb__pb2.LoginRequest.SerializeToString,
            schema_dot_immudb__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/immudb.ImmuService/Logout',
            schema_dot_immudb__pb2.LogoutRequest.SerializeToString,
            schema_dot_immudb__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/immudb.ImmuService/Set',
            schema_dot_immudb__pb2.SetRequest.SerializeToString,
            schema_dot_immudb__pb2.SetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/immudb.ImmuService/Get',
            schema_dot_immudb__pb2.GetRequest.SerializeToString,
            schema_dot_immudb__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MultiSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/immudb.ImmuService/MultiSet',
            schema_dot_immudb__pb2.MultiSetRequest.SerializeToString,
            schema_dot_immudb__pb2.MultiSetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Scan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/immudb.ImmuService/Scan',
            schema_dot_immudb__pb2.ScanRequest.SerializeToString,
            schema_dot_immudb__pb2.ScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/immudb.ImmuService/Delete',
            schema_dot_immudb__pb2.DeleteRequest.SerializeToString,
            schema_dot_immudb__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
