# \city_chain_project\DAGs\libs\algorithm\poh_holdmetrics\poh_holdmetrics_python\poh_holdmetrics\protocols\hold_pb2.py
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hold.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'hold.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nhold.proto\x12\x03poh\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xa4\x01\n\x07HoldMsg\x12\x10\n\x08token_id\x18\x01 \x01(\t\x12\x11\n\tholder_id\x18\x02 \x01(\t\x12)\n\x05start\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\'\n\x03\x65nd\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06weight\x18\x05 \x01(\x01J\x04\x08\x06\x10\x07J\x04\x08\x07\x10\x08J\x04\x08\x08\x10\t\"*\n\x07HoldAck\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\tJ\x04\x08\x03\x10\x04\"\x8e\x01\n\x08HoldStat\x12\x11\n\tholder_id\x18\x01 \x01(\t\x12\x15\n\rtotal_seconds\x18\x02 \x01(\x03\x12\x16\n\x0eweighted_score\x18\x03 \x01(\x01\x12.\n\nupdated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampJ\x04\x08\x05\x10\x06J\x04\x08\x06\x10\x07J\x04\x08\x07\x10\x08\x32\x92\x01\n\x0bHoldMetrics\x12+\n\tBroadcast\x12\x0c.poh.HoldMsg\x1a\x0c.poh.HoldAck(\x01\x30\x01\x12$\n\x06Record\x12\x0c.poh.HoldMsg\x1a\x0c.poh.HoldAck\x12\x30\n\x05Stats\x12\x16.google.protobuf.Empty\x1a\r.poh.HoldStat0\x01\x32\x7f\n\x10HoldMetricsQuery\x12\x36\n\x0bGetSnapshot\x12\x16.google.protobuf.Empty\x1a\r.poh.HoldStat0\x01\x12\x33\n\x0bHealthCheck\x12\x16.google.protobuf.Empty\x1a\x0c.poh.HoldAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hold_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HOLDMSG']._serialized_start = 82
  _globals['_HOLDMSG']._serialized_end = 246
  _globals['_HOLDACK']._serialized_start = 248
  _globals['_HOLDACK']._serialized_end = 290
  _globals['_HOLDSTAT']._serialized_start = 293
  _globals['_HOLDSTAT']._serialized_end = 435
  _globals['_HOLDMETRICS']._serialized_start = 438
  _globals['_HOLDMETRICS']._serialized_end = 584
  _globals['_HOLDMETRICSQUERY']._serialized_start = 586
  _globals['_HOLDMETRICSQUERY']._serialized_end = 713
# @@protoc_insertion_point(module_scope)
