{
 "title": "Immudb",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(immudb_db_size_bytes, instance)"
    }
   },
   {
    "name": "db",
    "label": "Database",
    "query": {
     "query": "label_values(immudb_db_size_bytes{instance=~\"$instance\"}, db)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Database size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "immudb_db_size_bytes{instance=~\"$instance\",db=~\"$db\"}",
     "legendFormat": "{{db}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Database growth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(immudb_db_size_bytes{instance=~\"$instance\",db=~\"$db\"}[$__rate_interval])",
     "legendFormat": "{{db}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Stored Entries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "immudb_number_of_stored_entries{instance=~\"$instance\",db=~\"$db\"}",
     "legendFormat": "{{db}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Stored Entries Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "rate(immudb_number_of_stored_entries{instance=~\"$instance\",db=~\"$db\"}[$__rate_interval])",
     "legendFormat": "{{db}} ({{instance}})"
    }
   ]
  },
  { "title": "Indexer statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Indexed %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "immudb_last_indexed_trx_id{instance=~\"$instance\",db=~\"$db\"}/immudb_last_committed_trx_id{instance=~\"$instance\",db=~\"$db\"}",
     "legendFormat": "{{db}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Indexing / commit rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "rate(immudb_last_indexed_trx_id{instance=~\"$instance\",db=~\"$db\"}[$__rate_interval])",
     "legendFormat": "Idx {{db}} ({{instance}})"
    },
    {
     "expr": "rate(immudb_last_committed_trx_id{instance=~\"$instance\",db=~\"$db\"}[$__rate_interval])",
     "legendFormat": "Cmt {{db}} ({{instance}})"
    }
   ]
  },
  {
   "title": "TRXs left to index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "immudb_last_committed_trx_id{instance=~\"$instance\",db=~\"$db\"}-immudb_last_indexed_trx_id{instance=~\"$instance\",db=~\"$db\"}",
     "legendFormat": "{{db}} ({{instance}})"
    }
   ]
  },
  {
   "title": "TRX count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "immudb_last_committed_trx_id{instance=~\"$instance\",db=~\"$db\"}",
     "legendFormat": "{{db}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Btree cache size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "label_replace(immudb_btree_cache_size{instance=~\"$instance\",id=~\".*/$db/index\"}, \"db\", \"$1\", \"id\", \".*/([^/]*)/index\")",
     "legendFormat": "{{db}} ({{instance}})"
    }
   ]
  },
  {
   "title": "BTree cache hit%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(\n    rate(immudb_btree_cache_hit{instance=~\"$instance\",id=~\".*/$db/index\"}[$__rate_interval]) /\n    (\n        rate(immudb_btree_cache_miss{instance=~\"$instance\",id=~\".*/$db/index\"}[$__rate_interval])+\n        rate(immudb_btree_cache_hit{instance=~\"$instance\",id=~\".*/$db/index\"}[$__rate_interval])\n    ),\n\"db\", \"$1\", \"id\", \".*/([^/]*)/index\")",
     "legendFormat": "{{db}} ({{instance}})"
    }
   ]
  },
  {
   "title": "BTree insights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "BTree depth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "label_replace(immudb_btree_depth{instance=~\"$instance\",id=~\".*/$db/index\"},\"db\", \"$1\", \"id\", \".*/([^/]*)/index\")",
       "legendFormat": "{{db}} ({{instance}})"
      }
     ]
    },
    {
     "title": "BTree inner nodes children distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
     "targets": [
      {
       "expr": "sum(rate(immudb_btree_inner_node_entries_bucket{instance=~\"$instance\",id=~\".*/$db/index\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "BTree leaf nodes children distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
     "targets": [
      {
       "expr": "sum(rate(immudb_btree_leaf_node_entries_bucket{instance=~\"$instance\",id=~\".*/$db/index\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Flush rate - entries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "label_replace(\n  rate(immudb_btree_flushed_entries_total{instance=~\"$instance\",id=~\".*/$db/index\"}[$__rate_interval]),\n\"db\", \"$1\", \"id\", \".*/([^/]*)/index\")",
       "legendFormat": "{{db}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Flush progress - entries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
     "targets": [
      {
       "expr": "label_replace(\n  immudb_btree_flushed_entries_last_cycle{instance=~\"$instance\", id=~\".*/$db/index\"},\n\"db\", \"$1\", \"id\", \".*/([^/]*)/index\")",
       "legendFormat": "{{db}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Flush rate - nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "label_replace(\n  rate(immudb_btree_flushed_nodes_total{instance=~\"$instance\",id=~\".*/$db/index\"}[$__rate_interval]),\n\"db\", \"$1\", \"id\", \".*/([^/]*)/index\")",
       "legendFormat": "{{db}} {{kind}} nodes ({{instance}})"
      }
     ]
    },
    {
     "title": "Flush rate - nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
     "targets": [
      {
       "expr": "label_replace(\n  immudb_btree_flushed_nodes_last_cycle{instance=~\"$instance\",id=~\".*/$db/index\"},\n\"db\", \"$1\", \"id\", \".*/([^/]*)/index\")",
       "legendFormat": "{{db}} {{kind}} nodes ({{instance}})"
      }
     ]
    },
    {
     "title": "Compaction rate - entries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "label_replace(\n  rate(immudb_btree_compacted_entries_total{instance=~\"$instance\",id=~\".*/$db/index\"}[$__rate_interval]),\n\"db\", \"$1\", \"id\", \".*/([^/]*)/index\")",
       "legendFormat": "{{db}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Compaction progress - entries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 43 },
     "targets": [
      {
       "expr": "label_replace(\n  immudb_btree_compacted_entries_last_cycle{instance=~\"$instance\",id=~\".*/$db/index\"},\n\"db\", \"$1\", \"id\", \".*/([^/]*)/index\")"
      }
     ]
    },
    {
     "title": "Compaction rate - nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "label_replace(\n  rate(immudb_btree_compacted_nodes_total{instance=~\"$instance\",id=~\".*/$db/index\"}[$__rate_interval]),\n\"db\", \"$1\", \"id\", \".*/([^/]*)/index\")",
       "legendFormat": "{{db}} {{kind}} nodes ({{instance}})"
      }
     ]
    },
    {
     "title": "Compaction progress - nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 43 },
     "targets": [
      {
       "expr": "label_replace(\n  immudb_btree_compacted_nodes_last_cycle{instance=~\"$instance\",id=~\".*/$db/index\"},\n\"db\", \"$1\", \"id\", \".*/([^/]*)/index\")",
       "legendFormat": "{{db}} {{kind}} nodes ({{instance}})"
      }
     ]
    },
    {
     "title": "Nodes data size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(\n  immudb_btree_nodes_data_end{instance=~\"$instance\",id=~\".*/$db/index\"}-\n  immudb_btree_nodes_data_begin{instance=~\"$instance\",id=~\".*/$db/index\"},\n\"db\", \"$1\", \"id\", \".*/([^/]*)/index\")",
       "legendFormat": "{{db}} ({{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "S3 statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "immudb_remoteapp_open_time (sec)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(immudb_remoteapp_open_time_bucket{instance=~\"$instance\"}) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "S3 I/O",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(immudb_remoteapp_read_bytes{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}