dir = "D:\\city_chain_project\\network\\DB\\immudb\\data\\tests\\login\\southamerica"
# address = "192.168.3.8" テスト用に下記のlocalhost を使用
address = "127.0.0.6"
port = 3328
metrics-address = "127.0.0.6:9503/metrics"
defaultDatabase = "southamerica"   # ← ここでデータベース名を指定

[grpc]
enabled = true
port = 3328
