dir = "D:\\city_chain_project\\network\\DB\\immudb\\data\\tests\\login\\northamerica"
# address = "192.168.3.8" テスト用に下記のlocalhost を使用
address = "127.0.0.5"
port = 3327
metrics-address = "127.0.0.5:9502/metrics"
defaultDatabase = "northamerica"   # ← ここでデータベース名を指定

[grpc]
enabled = true
port = 3327
