dir = "D:\\city_chain_project\\network\\DB\\immudb\\data\\tests\\login\\asia"
# address = "192.168.3.8" テスト用に下記のlocalhost を使用
address = "127.0.0.1"
port = 3323
metrics-address = "127.0.0.1:9498/metrics"
defaultDatabase = "asia"   # ← ここでデータベース名を指定

[grpc]
enabled = true
port = 3323
