dir = "D:\\city_chain_project\\network\\DB\\immudb\\data\\tests\\login\\europe"
# address = "192.168.3.8" テスト用に下記のlocalhost を使用
address = "127.0.0.2"
port = 3324
metrics-address = "127.0.0.2:9499/metrics"
defaultDatabase = "europe"   # ← ここでデータベース名を指定

[grpc]
enabled = true
port = 3324
