dir = "D:\\city_chain_project\\network\\DB\\immudb\\data\\tests\\login\\australia"
# address = "192.168.3.8" テスト用に下記のlocalhost を使用
address = "127.0.0.3"
port = 3325
metrics-address = "127.0.0.3:9500/metrics"
defaultDatabase = "australia"   # ← ここでデータベース名を指定

[grpc]
enabled = true
port = 3325
