dir = "D:\\city_chain_project\\network\\DB\\immudb\\data\\tests\\login\\africa"
# address = "192.168.3.8" テスト用に下記のlocalhost を使用
address = "127.0.0.4"
port = 3326
metrics-address = "127.0.0.4:9501/metrics"
defaultDatabase = "africa"   # ← ここでデータベース名を指定

[grpc]
enabled = true
port = 3326
