name: _Release Images (reusable)
on:
  workflow_call:
    inputs:
      service_prefix:  # 例: poh_holdmetrics
        required: true
        type: string
    secrets:
      GHCR_TOKEN:
        required: true
jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/${{ github.repository_owner }}
      VERSION: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - run: python tools/gen.py --services services.yaml --out .
      - name: Build & Push
        run: |
          docker buildx bake -f docker-bake.generated.hcl --push \
            --set ${{ inputs.service_prefix }}-http-svc.tags="${REGISTRY}/${{ inputs.service_prefix }}-http:latest,${REGISTRY}/${{ inputs.service_prefix }}-http:${VERSION}" \
            --set ${{ inputs.service_prefix }}-grpc-svc.tags="${REGISTRY}/${{ inputs.service_prefix }}-grpc:latest,${REGISTRY}/${{ inputs.service_prefix }}-grpc:${VERSION}"
