name: build_poh_holdmetrics_rust_wheels
on: { workflow_dispatch: {} }

jobs:
  win-wheel:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
        # リポジトリ直下からの相対パス（/ を使う）
        working-directory: DAGs/libs/algorithm/poh_holdmetrics/poh_holdmetrics_rust

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Show versions & where am I
        run: |
          pwd
          python -V
          rustc -V
          cargo -V
          ls

      - name: Install maturin
        run: pip install -U maturin

      - name: Build wheel (PyO3)
        run: maturin build --release --features python --manifest-path Cargo.toml --out dist

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: poh_holdmetrics_rust-win
          path: target/wheels/*.whl
