# \city_chain_project\.github\workflows\pre-commit.yaml
name: pre-commit
on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install pre-commit
      # 変更ファイルのみ対象にする（PR時やpush時の無駄撃ち防止）
      - name: Run pre-commit (changed files only)
        run: |
          git fetch origin ${{ github.base_ref || 'main' }} --depth=1 || true
          BASE_REF=${{ github.base_ref || 'origin/main' }}
          CHANGED=$(git diff --name-only "$BASE_REF"...HEAD | tr '\n' ' ')
          if [ -z "$CHANGED" ]; then
            echo "No changed files"; exit 0
          fi
          pre-commit run --files $CHANGED
