# \city_chain_project\.github\workflows\release-images-poh_holdmetrics.yml
name: Release Images (poh_holdmetrics)

on:
  push:
    tags:
      - "v*"

# ← ここが重要（呼び出し側で packages: write を許可）
permissions:
  contents: read
  packages: write

jobs:
  call-reusable:
    uses: ./.github/workflows/_release-images-reusable.yml
    with:
      registry: ghcr.io/satoshinakamoto1024     # ← 小文字必須！
      version: ${{ github.ref_name }}
      http_target: poh_holdmetrics-http-svc     # gen.py の target 名に一致
      grpc_target: poh_holdmetrics-grpc-svc
