name: Release Images
on:
  push:
    tags:
      - "v*"

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      REGISTRY: ghcr.io/<your-org-or-user>
      VERSION: ${{ github.ref_name }}  # v0.1.0 など
    steps:
      - uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate bake/compose
        run: python tools/gen.py --services services.yaml --out .

      - name: Build & Push images (http/grpc)
        run: |
          docker buildx bake -f docker-bake.generated.hcl --push \
            --set poh_holdmetrics-http-svc.tags="${REGISTRY}/poh_holdmetrics-http:latest,${REGISTRY}/poh_holdmetrics-http:${VERSION}" \
            --set poh_holdmetrics-grpc-svc.tags="${REGISTRY}/poh_holdmetrics-grpc:latest,${REGISTRY}/poh_holdmetrics-grpc:${VERSION}"
