name: Release Wheels (simple)
on:
  push:
    tags:
      - "v*"

jobs:
  build-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          protoc --version

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install maturin==1.5.1 build twine

      # Rust wheels を作る（features=python）
      - name: Build rust wheels
        run: |
          maturin build \
            -m DAGs/libs/algorithm/poh_holdmetrics/poh_holdmetrics_rust/Cargo.toml \
            --release --features python

      # Python ラッパ（sdist + wheel）
      - name: Build python wrapper (sdist+wheel)
        working-directory: DAGs/libs/algorithm/poh_holdmetrics/poh_holdmetrics_python
        run: python -m build

      - name: Upload to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          twine upload --repository-url https://test.pypi.org/legacy/ \
            target/wheels/*.whl \
            DAGs/libs/algorithm/poh_holdmetrics/poh_holdmetrics_python/dist/*
