name: Release Images (simple)
on:
  push:
    tags:
      - "v*"

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate bake/compose
        run: python tools/gen.py --services services.yaml --out .

      - name: Build & Push (latest only)
        run: |
          docker buildx bake -f docker-bake.generated.hcl --push \
            --set poh_holdmetrics-http-svc.tags=ghcr.io/${{ github.repository_owner }}/poh_holdmetrics-http:latest \
            --set poh_holdmetrics-grpc-svc.tags=ghcr.io/${{ github.repository_owner }}/poh_holdmetrics-grpc:latest
